version: "3.4"
services:
    mongo:
        image: mongo
    flask:
        image: abaayd/bol-bands-algo_flask:$TAG
        ports:
            - "8000:8000"
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - FLASK_ENV=production
        links:
            - mongo
        depends_on:
            - mongo
    server:
        image: abaayd/bol-bands-algo_server:$TAG
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=${MONGODB_URI}
            - FLASK_BASE_URL=http://flask:8000/api
        links:
            - mongo
            - flask
        depends_on:
            - mongo
            - flask
    client:
        image: abaayd/bol-bands-algo_client:$TAG
        ports:
            - "8081:80"
        environment:
            - VUE_APP_HTTP_SERVER_URI=${VUE_APP_HTTP_SERVER_URI}
            - VUE_APP_WS_SERVER_URI=${VUE_APP_WS_SERVER_URI}
