version: "3"
services:
    mongo:
        image: mongo
    web:
        image: abaayd/bol-bands-algo_server:$TAG
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=${MONGODB_URI}
        links:
            - mongo
        depends_on:
            - mongo
