version: "3.4"
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  flask:
    build:
      context: ./bol-bands-algo_flask
      target: dev
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bolBandsDB
      - FLASK_ENV=development
      - FLASK_APP=app
    links:
      - mongo
    depends_on:
      - mongo
    volumes:
      - ./bol-bands-algo_flask:/bol-bands-algo_flask
  server:
    build:
      context: ./bol-bands-algo_server
      target: dev
    ports:
      - "8080:8080"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/bolBandsDB
      - FLASK_BASE_URL=http://flask:5000/api
    links:
      - mongo
      - flask
    depends_on:
      - mongo
      - flask
    volumes:
      - ./bol-bands-algo_server:/server
  client:
    build:
      context: ./bol-bands-algo_client
      target: dev
    ports:
      - "8081:8080"
    environment:
      - VUE_APP_HTTP_SERVER_URI=http://localhost:8080
      - VUE_APP_WS_SERVER_URI=ws://localhost:8080
    volumes:
      - ./bol-bands-algo_client/src:/app/src
