version: "3"
services:
    mongo:
        image: mongo
    web:
        build: ./bol-bands-algo_server
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=${MONGODB_URI}
        links:
            - mongo
        depends_on:
            - mongo
