version: "3.4"
services:
    mongo:
        image: mongo
    server:
        image: abaayd/bol-bands-algo_server:$TAG
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=${MONGODB_URI}
        links:
            - mongo
        depends_on:
            - mongo
    client:
        image: abaayd/bol-bands-algo_client:$TAG
        ports:
            - "8081:80"
        environment:
            - VUE_APP_HTTP_SERVER_URI=${VUE_APP_HTTP_SERVER_URI}
            - VUE_APP_WS_SERVER_URI=${VUE_APP_WS_SERVER_URI}
