version: "3"
services:
    mongo:
        image: mongo
    web:
        build: .
        ports:
            - "8080:8080"
        environment:
            - MONGODB_URI=mongodb://mongo:27017/bolBands
        links:
            - mongo
        depends_on:
            - mongo
        volumes:
            - .:/server
            - /server/node_modules
