version: 2
jobs:
    build:
        docker:
            - image: circleci/node:lts
            - image: circleci/mongo
        steps:
            - checkout
            - setup_remote_docker:
                  docker_layer_caching: true
            - add_ssh_keys:
                  fingerprints:
                      - "ed:ee:e4:4d:0e:fc:a6:d2:ad:e1:e3:67:62:c1:4f:cf"
            - run:
                  name: Build and push Docker image
                  command: |
                      TAG=0.1.$CIRCLE_BUILD_NUM
                      docker build -t abaayd/bol-bands-algo_server:$TAG -t abaayd/bol-bands-algo_server:latest ./bol-bands-algo_server
                      docker build -t abaayd/bol-bands-algo_client:$TAG -t abaayd/bol-bands-algo_client:latest ./bol-bands-algo_client
                      docker login -u $DOCKER_USER -p $DOCKER_PASS
                      docker push abaayd/bol-bands-algo_server
                      docker push abaayd/bol-bands-algo_client
            - run:
                  name: SSH into droplet test
                  command: |
                      TAG=0.1.$CIRCLE_BUILD_NUM
                      ssh -oStrictHostKeyChecking=no -v root@$DROPLET_IP "cd /root; export MONGODB_URI=$MONGODB_URI; export TAG=$TAG; ./deploy.sh"
