version: 2
jobs:
    build:
        docker:
            - image: circleci/node:lts
            - image: circleci/mongo
        steps:
            - setup_remote_docker:
                  docker_layer_caching: true
            - add_ssh_keys:
                  fingerprints:
                      - "ed:ee:e4:4d:0e:fc:a6:d2:ad:e1:e3:67:62:c1:4f:cf"
            - checkout
            - run:
                  name: Build and push Docker image
                  command: |
                      docker build ./bol-bands-algo_server
                      docker login -u $DOCKER_USER -p $DOCKER_PASS
                      docker push abaayd/bol-bands-algo_server:@latest
            - run:
                  name: SSH into droplet test
                  command: |
                      ssh -oStrictHostKeyChecking=no -v root@$DROPLET_IP "cd /root; ./deploy.sh"
